/*  Repository List */
export const GET_REPOSITORY_LIST_START = 'GET_REPOSITORY_LIST_START';
export const GET_REPOSITORY_LIST_SUCCESS = 'GET_REPOSITORY_LIST_SUCCESS';
export const GET_REPOSITORY_LIST_FAIL = 'GET_REPOSITORY_LIST_FAIL';

/*  Repository */
export const GET_REPOSITORY_START = 'GET_REPOSITORY_START';
export const GET_REPOSITORY_SUCCESS = 'GET_REPOSITORY_SUCCESS';
export const GET_REPOSITORY_FAIL = 'GET_REPOSITORY_FAIL';

/*  Contributor List */
export const GET_CONTRIBUTOR_LIST_START = 'GET_CONTRIBUTOR_LIST_START';
export const GET_CONTRIBUTOR_LIST_SUCCESS = 'GET_CONTRIBUTOR_LIST_SUCCESS';
export const GET_CONTRIBUTOR_LIST_FAIL = 'GET_CONTRIBUTOR_LIST_FAIL';
export const EMPTY_CONTRIBUTOR_LIST = 'EMPTY_CONTRIBUTOR_LIST';

/*  Favorites */
export const SET_FAVORITES_IDS = 'SET_FAVORITES_IDS';